config/routes.rb
Yandextopfeed::Application.routes.draw do

  resources :feeds, {only: [:index, :update]} do 
  	collection {
  		get :out_by_options
  		get :put_feeds
  	}
  end
  get '/out_by_options' => 'feeds#out_by_options'
  root to: 'feeds#index'

end

app/models/feed.rb
# encoding: utf-8
require 'open-uri'
class Feed < ActiveRecord::Base
	YA_RSS_URL = 'http://news.yandex.ru/index.rss'

  attr_accessible :title, :body, :url, :published_at, :guid, :is_checked

  validates :title, presence: true
  validates :body, presence: true
  validates :url, presence: true

  def self.put_feeds
  	# feed = Feedzirra::Feed.fetch_and_parse(YA_RSS_URL)
  	# add_entries(feed.entries)
    page = Nokogiri::HTML(open("http://yandex.ru").read).xpath("//div[@class = 'b-news']")[0]
    lists = page.xpath("//ul[@class = 'b-news-list']")
    parse_list(lists[0], 'Новости')
    parse_list(lists[1], 'В Москве')
    parse_list(lists[2], 'В блогах')
  end

  def self.return_by_time(time_option, page)
    time = DateTime.now - case time_option
      when 'all'
        2.year
      when 'hour'
        1.hour
      when '3hour'
        3.hour
      when 'day'
        1.day
      when 'week'
        1.week
      when '2week'
        2.week
      end
    feeds = Feed.paginate(page: page, per_page: 10)
      .where(published_at: time..Time.now)
      .order('published_at DESC')
  end

  def self.return_by_text(feeds, text)
    # out_feeds = []
    # feeds.each do |f|
    #   text.split(", ").each do |t|
    #     out_feeds.push(f) if f.title.index(t).present? || f.body.index(t).present?
    #   end
    # end
    # out_feeds.compact
    text.split(", ").each do |t|
      if Rails.env.production?
        feeds = feeds.where('(title ILIKE ?) OR (body ILIKE ?)', "%#{t}%", "%#{t}%")
      else
        feeds = feeds.where('(title LIKE ?) OR (body LIKE ?)', "%#{t}%", "%#{t}%")
      end
    end
    feeds
  end

  private

  def self.parse_list(list, i)
    list.element_children.each do |li|
      url = li.css('a')[0]['href']
      unless exists? url: url
        create!(
          title: i,
          body: li.content.insert(2, ' '),
          url: url,
          published_at: Time.now)
      end
    end
  end
  
  def self.add_entries(entries)
    entries.each do |entry|
      unless exists? :guid => entry.id
        create!(
          title:        entry.title,
          body:      		entry.summary,
          url:          entry.url,
          published_at: entry.published,
          guid:         entry.id
        )
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
# encoding: utf-8
class FeedsController < ApplicationController 

	def index
		@feeds = Feed.paginate(page: params[:page], per_page: 10).order('published_at DESC')
		@time_option = 'all'
		@check_option = false
	end

	def update
		@feed = Feed.find(params[:id])
		@feed.update_attributes(params[:feed])
		respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
	end

	def out_by_options
		@time_option = params[:time_option]
		@text_option = params[:text_option]
		@check_option = params[:check_option] == 'true' ? true : false
		@feeds = Feed.return_by_time(@time_option, params[:page])
		@feeds = Feed.return_by_text(@feeds, @text_option) if @text_option.present?
		@feeds = @feeds.where(is_checked: @check_option) if @check_option
		respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
	end

	def put_feeds
		Feed.put_feeds
		@time_option = params[:time_option]
		@feeds = Feed.return_by_time(@time_option, params[:page])
		respond_to do |format|
      format.html { redirect_to root_url(page: params[:page]) }
      format.js
    end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feeds/_check_options.html.haml
- if @check_option
	= link_to image_tag( 'checked.png'), '#', { :class=>"thumbnail", style: 'width: 23px;', id: 'check_options', name: 'true'}
- else
	= link_to image_tag( 'unchecked.png'), '#', { :class=>"thumbnail", style: 'width: 23px;', id: 'check_options', name: 'false'}

app/views/feeds/_feeds_list.html.haml
- @feeds.each do |f|
	%li#feed-item
		.row
			.span11{style: "margin-left: 0px;"}
				= link_to f.body, f.url
				%font{color: "#999"}
					= "(#{f.title})"
			.span1.is_checked{style: "width: 16px;"}
				= render partial: 'feeds/is_checked', locals: {f: f}
		.row{style: "margin-left: 10px"}
			%h6 
				= f.published_at.strftime("%d.%m.%Y %H:%M")

app/views/feeds/_is_checked.html.haml
- if f.is_checked?
	= link_to image_tag('checked.png'), feed_path(f, :feed => { is_checked: false}), method: :put, remote: true, id: f.id
- else
	= link_to image_tag('unchecked.png'), feed_path(f, :feed => { is_checked: true}), method: :put, remote: true, id: f.id

app/views/feeds/_paginate.html.haml
= will_paginate @feeds

app/views/feeds/index.html.haml
.page-header
	.row	
		.span9{style: "margin-left: 40px"}
			%h4#yandex-link 
				Топ-новости с
				= link_to 'Яндекса', 'http://yandex.ru'
		.span1{style: "margin-left: 135px;"}
			%h5
				= link_to 'справка', '#', "data-reveal-id" => "myModal"
.span12
	.row#options
		.span4
			Показывать
			= select_tag "time_options", options_for_select({"все" => "all", "за час" => "hour", "за три часа" => "3hour", "за сутки" => "day", "за неделю" => "week", "за две недели" => "2week"}), options = {style: "width: 150px; margin-left: 10px;"}
		.span5
			Фильтр
			= text_field :text, :options, style: "width: 150px; margin-left: 10px;"
		.span1#check_options_render{style: "width: 45px;"}
			= render 'check_options'
		.span1{style: "margin-left: 0px;"}
			= link_to image_tag( 'load.png'), '#', { :class=>"thumbnail", style: 'width: 23px;', id: 'load_feeds'}
	%ul.span12#feeds-list
		= render 'feeds_list'
	.flickr_pagination.span12#pagination
		= render 'paginate'

.reveal-modal#myModal
	%h1 Что это и как этим пользоваться?
	%p 
		Это небольшое приложение для мониторинга топ5 новостей с главной страницы yandex.ru.
	%p
		Каждый час сюда загружаются новости с главной яндекса по всем блокам (Новости, в Москве, в Блогах) и отображаются общим списком.
		Вы можете сами в любой момент догрузить актуальные новости, нажав кнопку 
		= image_tag "load.png", style: "width: 15px;" 
		Новости старше двух недель удаляются автоматически.
	%p
		Работа со списком новостей:
	%p
		* Вы можете фильтровать новости по времени публикации, выбрав из списка вариант отображения (за последний час, три часа, неделю и т.д)
	%p
		* Можно фильтровать список в зависимости от содержимого заголовка следующим образом: через запятую в специальное поле вбиваете ключевые слова, по которым будет вестись поиск. Соответственно будут отображаться новости, содержащие все ключевые слова. Например, вы можете набрать "в Москве", для отображения новостей только из этого блока, а затем через запятую "Путин", для уточнения запроса. Таким образом будут отображаться новости только из блока "в Москве", содержащие в заголовке слово "Путин".
	%p
		* Новость можно пометить как избранную ("нужную"), кликнув на 
		= image_tag "unchecked.png", style: "width: 15px;" 
		напротив соответствующего заголовка. Чтобы просмотреть все "нужные" новости, нужно кликнуть на кнопку
		= image_tag "unchecked.png", style: "width: 15px;" 
		рядом с кнопкой загрузки.
	%p 
		Вот и все, все просто. Если возникнут вопросы или пожелания доработки, исправления ошибок и т.п., думаю, вы знаете к кому обратиться. Надеюсь, приложение будет для вас удобным в использовании, а самое главное, полезным. 
	%a.close-reveal-modal
		&#215;

app/views/feeds/out_by_options.js.erb
$("#feeds-list").html("<%= escape_javascript(render ('feeds/feeds_list')) %>");
$("#pagination").html("<%= escape_javascript(render ('feeds/paginate')) %>");
$("#check_options_render").html("<%= escape_javascript(render ('feeds/check_options')) %>");

app/views/feeds/out_by_time.js.erb
$("#feeds-list").html("<%= escape_javascript(render ('feeds/feeds_list')) %>");
$("#pagination").html("<%= escape_javascript(render ('feeds/paginate')) %>");

app/views/feeds/put_feeds.js.erb
$("#feeds-list").html("<%= escape_javascript(render ('feeds/feeds_list')) %>");
$("#pagination").html("<%= escape_javascript(render ('feeds/paginate')) %>");

app/views/feeds/update.js.erb
$(".is_checked").find("#<%= @feed.id %>").html("<%= escape_javascript(render partial: 'feeds/is_checked', locals: {f: @feed}) %>");

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title Calendar
		= stylesheet_link_tag    "bootstrap", :media => "all"
		= stylesheet_link_tag    "application", :media => "all"
		= stylesheet_link_tag    "reveal", :media => "all"
		= javascript_include_tag "application"
		= javascript_include_tag "jquery.reveal"
		= csrf_meta_tags
	%body
		.container{style: "min-height: 100%;"}
			= yield
		%footer.footer.container
			%h6
				by
				= link_to 'G.Shumilkin', 'https://github.com/shumShum/yandextopfeed'
				, 2013